/**
 * useSandboxStream — React hook for WebSocket-based code streaming.
 *
 * Connects to the FastAPI ``/ws/codegen`` endpoint and streams JSX code
 * tokens as they are generated by the backend LLM.
 *
 * State machine:
 *   idle ──send──► streaming ──done──► complete
 *                      │
 *                   error ──────────► error
 *
 * Usage:
 *   const { code, status, error, generate, reset } = useSandboxStream(wsUrl);
 *   generate("build a counter");   // starts streaming
 */

'use client';

import { useCallback, useEffect, useRef, useState } from 'react';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type StreamStatus = 'idle' | 'connecting' | 'streaming' | 'complete' | 'error';

export interface SandboxStreamState {
  /** Accumulated JSX code received so far. */
  code: string;
  /** Current streaming lifecycle state. */
  status: StreamStatus;
  /** Human-readable error message when status === 'error'. */
  error: string | null;
  /** Send a prompt to begin code generation. */
  generate: (prompt: string) => void;
  /** Reset accumulated code and return to idle. */
  reset: () => void;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const RECONNECT_BASE_MS    = 1_000;
const RECONNECT_MAX_MS     = 16_000;
const MAX_RECONNECT_TRIES  = 5;

// ---------------------------------------------------------------------------
// Hook
// ---------------------------------------------------------------------------

export function useSandboxStream(wsUrl: string): SandboxStreamState {
  const [code,   setCode]   = useState('');
  const [status, setStatus] = useState<StreamStatus>('idle');
  const [error,  setError]  = useState<string | null>(null);

  // Refs so callbacks never stale-close over state
  const wsRef           = useRef<WebSocket | null>(null);
  const codeBufferRef   = useRef('');
  const reconnectCount  = useRef(0);
  const reconnectTimer  = useRef<ReturnType<typeof setTimeout> | null>(null);
  const pendingPrompt   = useRef<string | null>(null);

  // -------------------------------------------------------------------------
  // Connect / reconnect
  // -------------------------------------------------------------------------

  const connect = useCallback(() => {
    // Clean up any existing socket
    if (wsRef.current) {
      wsRef.current.onclose   = null;
      wsRef.current.onerror   = null;
      wsRef.current.onmessage = null;
      wsRef.current.close();
      wsRef.current = null;
    }

    setStatus('connecting');

    const ws = new WebSocket(wsUrl);
    wsRef.current = ws;

    ws.onopen = () => {
      reconnectCount.current = 0;
      // If a prompt was queued before the socket was ready, send it now.
      if (pendingPrompt.current !== null) {
        ws.send(JSON.stringify({ prompt: pendingPrompt.current }));
        pendingPrompt.current = null;
        setStatus('streaming');
      } else {
        setStatus('idle');
      }
    };

    ws.onmessage = (ev: MessageEvent) => {
      let msg: { type: string; content?: string; detail?: string };
      try {
        msg = JSON.parse(ev.data as string);
      } catch {
        return;
      }

      switch (msg.type) {
        case 'token':
          if (typeof msg.content === 'string') {
            codeBufferRef.current += msg.content;
            setCode(codeBufferRef.current);
          }
          break;

        case 'done':
          setStatus('complete');
          break;

        case 'error':
          setStatus('error');
          setError(msg.detail ?? 'Unknown streaming error');
          break;

        default:
          break;
      }
    };

    ws.onerror = () => {
      // The close event fires right after; let onclose handle reconnection.
    };

    ws.onclose = (ev: CloseEvent) => {
      wsRef.current = null;

      // 1000 = normal closure (reset/unmount). Don't reconnect.
      if (ev.code === 1000) return;

      if (reconnectCount.current < MAX_RECONNECT_TRIES) {
        const delay = Math.min(
          RECONNECT_BASE_MS * 2 ** reconnectCount.current,
          RECONNECT_MAX_MS,
        );
        reconnectCount.current += 1;
        reconnectTimer.current = setTimeout(connect, delay);
      } else {
        setStatus('error');
        setError(`WebSocket closed (code ${ev.code}) after ${MAX_RECONNECT_TRIES} reconnect attempts.`);
      }
    };
  }, [wsUrl]);

  // -------------------------------------------------------------------------
  // Lifecycle
  // -------------------------------------------------------------------------

  useEffect(() => {
    connect();

    return () => {
      if (reconnectTimer.current) clearTimeout(reconnectTimer.current);
      if (wsRef.current) {
        wsRef.current.onclose = null;
        wsRef.current.close(1000, 'component unmounted');
        wsRef.current = null;
      }
    };
  }, [connect]);

  // -------------------------------------------------------------------------
  // Public API
  // -------------------------------------------------------------------------

  const generate = useCallback((prompt: string) => {
    codeBufferRef.current = '';
    setCode('');
    setError(null);

    const ws = wsRef.current;

    if (!ws || ws.readyState !== WebSocket.OPEN) {
      // Queue the prompt and reconnect; it will be sent in onopen.
      pendingPrompt.current = prompt;
      connect();
      return;
    }

    setStatus('streaming');
    ws.send(JSON.stringify({ prompt }));
  }, [connect]);

  const reset = useCallback(() => {
    codeBufferRef.current = '';
    setCode('');
    setStatus('idle');
    setError(null);
  }, []);

  return { code, status, error, generate, reset };
}
